spring:
  profiles:
    active:
      -dev
---
server:
  port: 8081

spring:
  profiles: dev
  application:
    name: iludan-service-picture

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6171/eureka
  instance:
    instance-id: iludan-service-picture
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 3

info:
  app.name: iludan-service-picture
  company.name: iludan
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

---
server:
  port: 8180
spring:
  profiles: beta
  application:
    name: iludan-service-picture

